name: Terraform PR Check
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform_plan:
    name: Terraform Plan for dev
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"
        working-directory: ./terraform
